apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: all-pod-default
spec:
  selector:
    matchExpressions:
      # pod-default requires selector, we need one to be always true
      - {key: fake-key, operator: NotIn, values: [fake-value]}
      # Exclude serving pod to separate serving config out (to be handled by serving sdk instead)
      - {key: serving.knative.dev/service, operator: DoesNotExist}
  desc: "all-pod-default"
  annotations:
    logging.zgtools.net/istio-init.ignore: "true"
    logging.zgtools.net/istio-proxy.ignore: "true"
    logging.zgtools.net/queue-proxy.ignore: "true"
    logging.zgtools.net/topic: "{{ logging_topic }}"
    logging.zgtools.net/wait.ignore: "true"
  labels:
    # These labels are needed for cost attribution
    zodiac.zillowgroup.net/environment: aianalytics_stage
    zodiac.zillowgroup.net/team: "{{ zodiac_team_name }}"
    zodiac.zillowgroup.net/service: "{{ zodiac_service }}"
  env:
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: KFP_SDK_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  # used by Metaflow Notify Email, to include in the body
  - name: ARGO_WORKFLOW_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.labels['workflows.argoproj.io/workflow']
  - name: K8S_CLUSTER_NAME
    value: aianalytics-stage-k8s-1
  - name: K8S_CLUSTER_ENV
    value: nonprod
  - name: K8S_DEVEX_ENV
    value: aianalytics_stage
  - name: CUSTOMER_CICD_ENV
    value: dev
  - name: METAFLOW_NOTIFY_EMAIL_SMTP_HOST
    value: "se3-smtp.uni.zillow.local"
  - name: METAFLOW_NOTIFY_EMAIL_SMTP_PORT
    value: "25"
  - name: METAFLOW_NOTIFY_EMAIL_FROM
    value: "ai-platform-alerts@zillowgroup.com"
  - name: METAFLOW_NOTIFY_EMAIL_BODY
    value: "Please goto <a href='https://analytics.pages.zgtools.net/artificial-intelligence/ai-platform/aip-docs/kubeflow/user_journeys/3_workflow_on_cluster/debugging_runs.html'>Debugging local and cluster runs<a/> for more information on how to debug failed runs."
  # Who to notify on error
  - name: METAFLOW_NOTIFY_ON_ERROR
    value: "{{ user_email }}"
  - name: KFP_RUN_URL_PREFIX
    value: "https://kubeflow.corp.stage-k8s.zg-aip.net/"
  - name: METAFLOW_DEFAULT_DATASTORE
    value: "s3"
  - name: METAFLOW_DEFAULT_METADATA
    value: "service"
  - name: METAFLOW_SERVICE_URL
    value: "https://kubeflow.int.stage-k8s.zg-aip.net/metaflow-service"
  - name: METAFLOW_DATASTORE_SYSROOT_S3
    value: "{{ s3://serve-datalake-zillowgroup/zillow/workflow_sdk/metaflow_28d/dev/None }}"
  - name: WAGGLE_DANCE_DEFAULT_ENVIRONMENT
    value: "STAGE"
  - name: WAGGLE_DANCE_DEV_ENDPOINT
    value: "thrift://waggledance.dev.infra.ana.zillow.net:48869"
  - name: WAGGLE_DANCE_STAGE_ENDPOINT
    value: "thrift://waggledance.infra.ana.zillow.net:48869"
  - name: WAGGLE_DANCE_PROD_READ_ONLY_ENDPOINT
    value: "thrift://waggledance-prod-ro.infra.ana.zillow.net:48869"
  - name: WAGGLE_DANCE_PROD_ENDPOINT
    value: "thrift://waggledance-prod.infra.ana.zillow.net:48869"
  - name: ODP_API_ROOT_URL
    value: "https://odp-api.int.stage-k8s.zg-aip.net"
  - name: AIP_STREAMZ_KAFKA_PRODUCER_SECRET
    value: "service_zg-dev-ai-platform-aip-infrastructure-streamz"